### ISSUE TITLE
가위,바위,보가 아닌 다른 것을 입력 했을 때 기능 추가

### ISSUE THREAD

**Issue by admauve** [admauve/week11_team3#4]

**Comment by yejun235** [comment]
import random

def play():
    user = input_choice()
    computer = random.choice(['R', 'S', 'P'])
    
    print(f"사용자: {user}, 컴퓨터: {computer}")
    
    if user == computer:
        return "비겼습니다."
    elif win(user, computer):
        return "이겼습니다."
    else:
        return "졌습니다."

def input_choice():
    while True:
        user = input("가위 = S, 바위 = R, 보 = P: ").upper()  # 대소문자 구분 없이 받기 위해 .upper() 사용
        if user in ['R', 'S', 'P']:
            return user
        print("잘못된 입력입니다. 가위(S), 바위(R), 보(P) 중 하나를 선택해 주세요.")

def win(player, opponent):
    return (player == 'R' and opponent == 'S') or \
           (player == 'S' and opponent == 'P') or \
           (player == 'P' and opponent == 'R')


print(play())
