### ISSUE TITLE
묵찌빠로 변형 기능 추가

### ISSUE THREAD

**Issue by admauve** [admauve/week11_team3#5]

**Comment by yejun235** [comment]
import random

def 가위바위보():
    user = input("가위(S), 바위(R), 보(P) 중 하나를 선택하세요: ")
    computer = random.choice(['R', 'S', 'P'])
    
    if user == computer:
        print("비겼습니다. 다시 가위바위보를 합니다.")
        return None  # 비긴 경우, 다시 가위바위보를 해야 함
    elif win(user, computer):
        print("사용자가 가위바위보에서 이겼습니다. 공격자가 됩니다!")
        return "user"
    else:
        print("컴퓨터가 가위바위보에서 이겼습니다. 공격자가 됩니다!")
        return "computer"

def 묵찌빠(attacker):
    while True:
        user = input("가위(S), 바위(R), 보(P) 중 하나를 선택하세요: ")
        computer = random.choice(['R', 'S', 'P'])
        print(f"사용자: {user}, 컴퓨터: {computer}")

        if user == computer:
            if attacker == "user":
                print("사용자가 묵찌빠에서 승리했습니다!")
            else:
                print("컴퓨터가 묵찌빠에서 승리했습니다!")
            break  # 공격자가 승리했으므로 게임 종료
        else:
            # 공격자 교체
            if win(user, computer):
                print("사용자가 이번 라운드에서 이겼습니다. 공격자가 됩니다!")
                attacker = "user"
            else:
                print("컴퓨터가 이번 라운드에서 이겼습니다. 공격자가 됩니다!")
                attacker = "computer"

def win(player, opponent):
    return (player == 'R' and opponent == 'S') or \
           (player == 'S' and opponent == 'P') or \
           (player == 'P' and opponent == 'R')

def 묵찌빠_게임():
    print("묵찌빠 게임을 시작합니다!")
    
    # 가위바위보로 공격자 결정
    attacker = None
    while attacker is None:
        attacker = 가위바위보()

    # 묵찌빠 진행
    묵찌빠(attacker)

# 게임 시작
묵찌빠_게임()

**Comment by leedosin** [comment]
### 

- [ ] - > [`_****_`](url)
